sudo: false
language: node_js
os:
  - linux
  - osx
node_js:
  - "node"
  - "12"
  - "10"
  - "9"
  - "8"
script:
  # run cspell on cspell using pre-commit
  # - pip install --user pre-commit
  # - pre-commit try-repo .

  # normal testing
  - npm install
  # the prepare script run during install currently does clean-build
  - npm test
  # - npm run lint-travis
  - npm run travis-coverage
  - npm run test-spec
  - node ./bin.js trace test
  - node ./bin.js "**/{*.ts,*.md}"
